# Generated by Django 3.0.4 on 2020-03-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_screening", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="clinic_type",
            field=models.CharField(
                choices=[
                    ("hiv_clinic", "HIV Clinic"),
                    ("ncd_clinic", "NCD Clinic"),
                    ("integrated_clinic", "Integrated Clinic"),
                ],
                default="integrated_clinic",
                max_length=25,
                verbose_name="From which type of clinic was the patient selected",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="lives_nearby",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Is the patient planning to remain in the catchment area for at least 6 months",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="qualifying_condition",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Does the patient have at least one of the following conditions: HIV, Diabetes and/or Hypertension",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="requires_acute_care",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=25,
                verbose_name="Does the patient require acute care including in-patient admission",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("random_sampling", "Random sampling"),
                    ("purposively_selected", "Purposively selected"),
                    ("retrospective", "Retrospective"),
                ],
                default="integrated_clinic",
                max_length=25,
                verbose_name="How was the patient selected for screening?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="clinic_type",
            field=models.CharField(
                choices=[
                    ("hiv_clinic", "HIV Clinic"),
                    ("ncd_clinic", "NCD Clinic"),
                    ("integrated_clinic", "Integrated Clinic"),
                ],
                default="integrated_clinic",
                max_length=25,
                verbose_name="From which type of clinic was the patient selected",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="lives_nearby",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Is the patient planning to remain in the catchment area for at least 6 months",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="qualifying_condition",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Does the patient have at least one of the following conditions: HIV, Diabetes and/or Hypertension",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="requires_acute_care",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=25,
                verbose_name="Does the patient require acute care including in-patient admission",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("random_sampling", "Random sampling"),
                    ("purposively_selected", "Purposively selected"),
                    ("retrospective", "Retrospective"),
                ],
                default="integrated_clinic",
                max_length=25,
                verbose_name="How was the patient selected for screening?",
            ),
        ),
    ]
