# Generated by Django 3.0.4 on 2020-04-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_screening", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="confirm_hospital_identifier",
            field=models.CharField(
                help_text="Retype the Hindu Mandal Hospital Number",
                max_length=25,
                verbose_name="Confirm Hospital Number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="ctc_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=25,
                null=True,
                verbose_name="CTC Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="hospital_identifier",
            field=models.CharField(
                db_index=True,
                help_text="Hindu Mandal Hospital Number",
                max_length=25,
                verbose_name="Hospital number",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="confirm_hospital_identifier",
            field=models.CharField(
                help_text="Retype the Hindu Mandal Hospital Number",
                max_length=25,
                verbose_name="Confirm Hospital Number",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="ctc_identifier",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                unique=True,
                verbose_name="CTC Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="hospital_identifier",
            field=models.CharField(
                help_text="Hindu Mandal Hospital Number",
                max_length=25,
                unique=True,
                verbose_name="Hospital number",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectscreening",
            unique_together={
                ("hospital_identifier", "ctc_identifier"),
                ("first_name", "dob", "initials", "last_name"),
            },
        ),
    ]
