# Generated by Django 3.0.4 on 2020-03-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_screening", "0002_auto_20200329_0438"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubjectscreening", name="lives_nearby",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectscreening", name="qualifying_condition",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectscreening", name="requires_acute_care",
        ),
        migrations.RemoveField(model_name="subjectscreening", name="lives_nearby",),
        migrations.RemoveField(
            model_name="subjectscreening", name="qualifying_condition",
        ),
        migrations.RemoveField(
            model_name="subjectscreening", name="requires_acute_care",
        ),
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="enrolment_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=50,
                verbose_name="Enrolment ID",
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="enrolment_identifier",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                unique=True,
                verbose_name="Enrolment ID",
            ),
        ),
    ]
