# Generated by Django 3.0.4 on 2020-05-12 00:09

from django.db import migrations
import django_crypto_fields.fields.encrypted_char_field
import edc_sites.models
import mapitio_screening.models.subject_screening


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_screening", "0003_auto_20200504_0014"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="subjectscreening",
            managers=[
                ("on_site", edc_sites.models.CurrentSiteManager()),
                (
                    "objects",
                    mapitio_screening.models.subject_screening.SubjectScreeningModelManager(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="confirm_ctc_identifier",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                help_text=" (Encryption: RSA local)",
                max_length=71,
                null=True,
                verbose_name="Confirm CTC Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="confirm_hospital_identifier",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                help_text="Retype the Hindu Mandal Hospital Identifier (Encryption: RSA local)",
                max_length=71,
                null=True,
                verbose_name="Confirm HMS Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="ctc_identifier",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                db_index=True,
                help_text=" (Encryption: RSA local)",
                max_length=71,
                null=True,
                verbose_name="CTC Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="file_number",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                db_index=True,
                help_text="Patient file number from Hindu Mandal Hospital (Encryption: RSA local)",
                max_length=71,
                verbose_name="Patient File number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="hospital_identifier",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                db_index=True,
                help_text="Hindu Mandal Hospital Identifier (Encryption: RSA local)",
                max_length=71,
                verbose_name="HMS Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="confirm_ctc_identifier",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                help_text=" (Encryption: RSA local)",
                max_length=71,
                null=True,
                verbose_name="Confirm CTC Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="confirm_hospital_identifier",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                help_text="Retype the Hindu Mandal Hospital Identifier (Encryption: RSA local)",
                max_length=71,
                null=True,
                verbose_name="Confirm HMS Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="ctc_identifier",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                help_text=" (Encryption: RSA local)",
                max_length=71,
                null=True,
                unique=True,
                verbose_name="CTC Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="file_number",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                help_text="Patient file number from Hindu Mandal Hospital (Encryption: RSA local)",
                max_length=71,
                unique=True,
                verbose_name="Patient File number",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="hospital_identifier",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                help_text="Hindu Mandal Hospital Identifier (Encryption: RSA local)",
                max_length=71,
                unique=True,
                verbose_name="HMS Identifier",
            ),
        ),
    ]
