# Generated by Django 3.0.4 on 2020-05-01 00:18

from django.db import migrations, models
import edc_model.validators.date


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_screening", "0003_auto_20200430_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="clinic_registration_date",
            field=models.DateField(
                validators=[
                    edc_model.validators.date.date_is_past,
                    edc_model.validators.date.date_is_not_now,
                ],
                verbose_name="Date patient was <u>first</u> enrolled to this clinic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="last_clinic_date",
            field=models.DateField(
                help_text="Date last seen according to information on the patient chart.",
                validators=[
                    edc_model.validators.date.date_is_past,
                    edc_model.validators.date.date_is_not_now,
                ],
                verbose_name="Date patient was <u>last</u> seen at this clinic",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="clinic_registration_date",
            field=models.DateField(
                validators=[
                    edc_model.validators.date.date_is_past,
                    edc_model.validators.date.date_is_not_now,
                ],
                verbose_name="Date patient was <u>first</u> enrolled to this clinic",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="last_clinic_date",
            field=models.DateField(
                help_text="Date last seen according to information on the patient chart.",
                validators=[
                    edc_model.validators.date.date_is_past,
                    edc_model.validators.date.date_is_not_now,
                ],
                verbose_name="Date patient was <u>last</u> seen at this clinic",
            ),
        ),
    ]
