# Generated by Django 2.2.5 on 2019-11-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetroModelEnrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_form_completion', models.DateField()),
                ('patient_hospital_ID', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE')])),
                ('date_patient_enrolled', models.DateField()),
                ('diagnose_made', models.DateField()),
                ('date_antiviral_commenced', models.DateField()),
                ('current_arv_regime', models.IntegerField(choices=[(1, 'AZT + 3TC + NVP'), (2, 'AZT + 3TC + EFV'), (3, 'AZT + 3TC + DTG'), (4, 'ABC + 3TC + EFV'), (5, 'ABC + 3TC + DTG'), (6, 'd4T + 3TC + NVP'), (7, 'd4T + 3TC + EFV'), (8, 'TDF + FTC + EFV'), (9, 'TDF + FTC + NVP'), (10, 'TDF + 3TC + EFV'), (11, 'TDF + 3TC + NVP'), (12, 'TDF + 3TC + DTG'), (13, 'TDF + FTC + DTG'), (14, 'TDF + 3TC + ATV/r'), (15, 'TDF + FTC + ATV/r'), (16, 'TDF + 3TC + LPV/r'), (17, 'AZT + 3TC + ATV/r'), (18, 'AZT + 3TC + LPV/r'), (19, 'ABC + 3TC + ATV/r'), (20, 'ABC + 3TC + LPV/r'), (21, 'TDF + FTC + LPV/R'), (22, 'DTG + (ABC/3TC) + ATV/r')])),
                ('prev_regimen_1_date_commenced', models.DateField()),
                ('prev_regimen_1_date_ended', models.DateField()),
                ('prev_regimen_1_reason_for_shift', models.TextField()),
                ('prev_regimen_2_date_commenced', models.DateField()),
                ('prev_regimen_2_date_commenced_date_ended', models.DateField()),
                ('prev_regimen_2_reason_for_shift', models.TextField()),
                ('patient_have_diabetes', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')])),
                ('diagnose_diabetes_made', models.DateField()),
                ('list_diabetes_treatment', models.TextField()),
                ('patient_have_hypertension', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')])),
                ('diagnose_hypertension_made', models.DateField()),
                ('list_hypertension_treatment', models.TextField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('blood_pressure_systolic', models.IntegerField()),
                ('blood_pressure_diastolic', models.IntegerField()),
                ('blood_glucose', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fasting_or_random', models.IntegerField(choices=[(1, 'Fasting'), (2, 'Random')])),
                ('total_cholesterol', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ldl', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hdl', models.DecimalField(decimal_places=1, max_digits=3)),
                ('triglycerides', models.DecimalField(decimal_places=1, max_digits=3)),
                ('serum_urea_levels', models.DecimalField(decimal_places=1, max_digits=3)),
                ('serum_creatinine_levels', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cd4_count', models.IntegerField()),
                ('cd4_count_date', models.DateField()),
                ('viral_load', models.IntegerField()),
                ('viral_load_date', models.DateField()),
                ('chest_x_ray', models.IntegerField(choices=[(1, 'Normal'), (2, 'Pneumonia'), (3, 'PCP'), (4, 'Cardiomegaly'), (5, 'Pleural effusion')])),
                ('ecg_findings', models.IntegerField(choices=[(1, 'Normal'), (2, 'Left ventricular hypertrophy'), (3, 'Ischaemic heart disease'), (4, 'Heart arrhythmias')])),
                ('echo_findings', models.IntegerField(choices=[(1, 'Normal'), (2, 'Left ventricular hypertrophy'), (3, 'Dystolic dysfunction'), (4, 'Cardiomyopathy'), (5, 'Other')])),
            ],
        ),
    ]
