# Generated by Django 2.2.5 on 2019-11-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retrospective", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="date_form_completion",
            new_name="Date_of_form_completion",
        ),
    ]
