# Generated by Django 2.2.5 on 2019-11-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retrospective", "0002_auto_20191114_1232"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIVRetrospectiveCohortFollowUpCRF",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Qn1_Date_of_form_completion", models.DateField()),
                ("Qn2_Patient_Hospital_ID", models.CharField(max_length=20)),
                ("Patients_initials", models.CharField(max_length=3)),
                ("Qn3_Date_patient_last_seen_at_the_clinic", models.DateField()),
                (
                    "Qn4_Is_the_patient_alive_and_in_care",
                    models.IntegerField(
                        choices=[
                            (1, "Yes, alive and in care at this clinic"),
                            (2, "Yes, alive and in care elsewhere"),
                            (3, "No, patient died"),
                        ]
                    ),
                ),
                (
                    "Qn5_Since_the_patient_started_at_this_clinic_have_they_developed_diabetes",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")]),
                ),
                (
                    "Qn6_If_YES_when_was_the_diagnosis_of_diabetes_made",
                    models.DateField(),
                ),
                ("Qn7_List_of_diabetes_treatment", models.TextField()),
                (
                    "Qn8_Since_the_patient_started_at_this_clinic_have_they_developed_hypertension",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")]),
                ),
                (
                    "Qn9_If_YES_when_was_the_diagnosis_of_hypertension_made",
                    models.DateField(),
                ),
                ("Qn10_List_of_hypertension_treatment", models.TextField()),
                ("Qn11_Stroke", models.IntegerField(choices=[(1, "Yes"), (2, "No")])),
                ("If_yes_to_Qn11_question_date_of_diagnosis", models.DateField()),
                (
                    "Qn12_Diabetic_foot",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")]),
                ),
                ("If_yes_to_Qn12_date_of_diagnosis", models.DateField()),
                (
                    "Qn13_Chronic_heart_failure",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")]),
                ),
                ("If_yes_to_Qn13_question_date_of_diagnosis", models.DateField()),
                (
                    "Qn14_Chronic_renal_failure",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")]),
                ),
                ("If_yes_to_Qn14_date_of_diagnosis", models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name="retromodelenrol", old_name="age", new_name="Age",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="blood_glucose",
            new_name="Blood_glucose",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="blood_pressure_diastolic",
            new_name="Blood_pressure_diastolic",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="blood_pressure_systolic",
            new_name="Blood_pressure_systolic",
        ),
        migrations.RenameField(
            model_name="retromodelenrol", old_name="cd4_count", new_name="CD4_count",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="chest_x_ray",
            new_name="Chest_X_ray_option_1",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="current_arv_regime",
            new_name="Current_ARV_regimen",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="cd4_count_date",
            new_name="Date_antiretroviral_therapy_commenced",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="date_antiviral_commenced",
            new_name="Date_of_CD4_count",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="date_patient_enrolled",
            new_name="Date_of_Viral_load",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="diagnose_diabetes_made",
            new_name="Date_patient_enrolled_at_the_clinic",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="patient_have_diabetes",
            new_name="Did_the_patient_have_Diabetes_when_they_started_attending_the_clinic",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="patient_have_hypertension",
            new_name="Did_the_patient_have_Hypertension_when_they_started_attending_the_clinic",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="ecg_findings",
            new_name="ECG_findings",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="echo_findings",
            new_name="ECHO_findings",
        ),
        migrations.RenameField(
            model_name="retromodelenrol", old_name="hdl", new_name="HDL",
        ),
        migrations.RenameField(
            model_name="retromodelenrol", old_name="height", new_name="Height",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="diagnose_hypertension_made",
            new_name="If_YES_when_was_the_diagnosis_of_diabetes_made",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="diagnose_made",
            new_name="If_YES_when_was_the_diagnosis_of_hypertension_made",
        ),
        migrations.RenameField(
            model_name="retromodelenrol", old_name="ldl", new_name="LDL",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="list_diabetes_treatment",
            new_name="List_of_diabetes_treatment_when_patient_started_attending_the_clinic",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="list_hypertension_treatment",
            new_name="List_of_hypertension_treatment_when_patient_started_attending_the_clinic",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="patient_hospital_ID",
            new_name="Patient_Hospital_ID",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="prev_regimen_1_date_commenced",
            new_name="Previous_regimen_1_Date_commenced",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="prev_regimen_1_date_ended",
            new_name="Previous_regimen_1_Date_ended",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="prev_regimen_1_reason_for_shift",
            new_name="Previous_regimen_1_Reason_for_shift",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="prev_regimen_2_date_commenced",
            new_name="Previous_regimen_2_Date_commenced",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="prev_regimen_2_date_commenced_date_ended",
            new_name="Previous_regimen_2_Date_ended",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="prev_regimen_2_reason_for_shift",
            new_name="Previous_regimen_2_Reason_for_shift",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="serum_creatinine_levels",
            new_name="Serum_creatinine_levels",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="serum_urea_levels",
            new_name="Serum_urea_levels",
        ),
        migrations.RenameField(
            model_name="retromodelenrol", old_name="sex", new_name="Sex",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="total_cholesterol",
            new_name="Total_cholesterol",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="triglycerides",
            new_name="Triglycerides",
        ),
        migrations.RenameField(
            model_name="retromodelenrol", old_name="viral_load", new_name="Viral_load",
        ),
        migrations.RenameField(
            model_name="retromodelenrol", old_name="waist", new_name="Waist",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="fasting_or_random",
            new_name="Was_this_a_fasting_or_random_blood_glucose",
        ),
        migrations.RenameField(
            model_name="retromodelenrol", old_name="weight", new_name="Weight",
        ),
        migrations.RenameField(
            model_name="retromodelenrol",
            old_name="viral_load_date",
            new_name="When_was_the_diagnosis_made",
        ),
        migrations.AddField(
            model_name="retromodelenrol",
            name="Chest_X_ray_option_2",
            field=models.IntegerField(
                choices=[
                    (1, "Normal"),
                    (2, "Pneumonia"),
                    (3, "PCP"),
                    (4, "Cardiomegaly"),
                    (5, "Pleural effusion"),
                ],
                default=None,
            ),
        ),
    ]
