# Generated by Django 2.2.5 on 2019-11-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospective', '0003_auto_20191114_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolmentPatientStartAtTheClinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_form_completion', models.DateField()),
                ('Patient_Hospital_ID', models.CharField(max_length=20)),
                ('Date_of_Birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Sex', models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE')])),
                ('Date_patient_enrolled_at_the_clinic', models.DateField()),
                ('When_was_the_diagnosis_made', models.DateField()),
                ('Date_antiretroviral_therapy_commenced', models.DateField()),
                ('Current_ARV_regimen', models.IntegerField(choices=[(1, 'AZT + 3TC + NVP'), (2, 'AZT + 3TC + EFV'), (3, 'AZT + 3TC + DTG'), (4, 'ABC + 3TC + EFV'), (5, 'ABC + 3TC + DTG'), (6, 'd4T + 3TC + NVP'), (7, 'd4T + 3TC + EFV'), (8, 'TDF + FTC + EFV'), (9, 'TDF + FTC + NVP'), (10, 'TDF + 3TC + EFV'), (11, 'TDF + 3TC + NVP'), (12, 'TDF + 3TC + DTG'), (13, 'TDF + FTC + DTG'), (14, 'TDF + 3TC + ATV/r'), (15, 'TDF + FTC + ATV/r'), (16, 'TDF + 3TC + LPV/r'), (17, 'AZT + 3TC + ATV/r'), (18, 'AZT + 3TC + LPV/r'), (19, 'ABC + 3TC + ATV/r'), (20, 'ABC + 3TC + LPV/r'), (21, 'TDF + FTC + LPV/R'), (22, 'DTG + (ABC/3TC) + ATV/r')])),
                ('Previous_regimen_1_Date_commenced', models.DateField()),
                ('Previous_regimen_1_Date_ended', models.DateField()),
                ('Previous_regimen_1_Reason_for_shift', models.TextField()),
                ('Previous_regimen_2_Date_commenced', models.DateField()),
                ('Previous_regimen_2_Date_ended', models.DateField()),
                ('Previous_regimen_2_Reason_for_shift', models.TextField()),
                ('Did_the_patient_have_Diabetes_when_they_started_attending_the_clinic', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')])),
                ('If_YES_when_was_the_diagnosis_of_diabetes_made', models.DateField()),
                ('List_of_diabetes_treatment_when_patient_started_attending_the_clinic', models.TextField()),
                ('Did_the_patient_have_Hypertension_when_they_started_attending_the_clinic', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')])),
                ('If_YES_when_was_the_diagnosis_of_hypertension_made', models.DateField()),
                ('List_of_hypertension_treatment_when_patient_started_attending_the_clinic', models.TextField()),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Waist', models.IntegerField()),
                ('Blood_pressure_systolic', models.IntegerField()),
                ('Blood_pressure_diastolic', models.IntegerField()),
                ('Blood_glucose', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Was_this_a_fasting_or_random_blood_glucose', models.IntegerField(choices=[(1, 'Fasting'), (2, 'Random')])),
                ('Total_cholesterol', models.DecimalField(decimal_places=1, max_digits=3)),
                ('LDL', models.DecimalField(decimal_places=1, max_digits=3)),
                ('HDL', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Triglycerides', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Serum_urea_levels', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Serum_creatinine_levels', models.DecimalField(decimal_places=1, max_digits=3)),
                ('CD4_count', models.IntegerField()),
                ('Date_of_CD4_count', models.DateField()),
                ('Viral_load', models.IntegerField()),
                ('Date_of_Viral_load', models.DateField()),
                ('Chest_X_ray_option_1', models.IntegerField(choices=[(1, 'Normal'), (2, 'Pneumonia'), (3, 'PCP'), (4, 'Cardiomegaly'), (5, 'Pleural effusion')])),
                ('Chest_X_ray_option_2', models.IntegerField(choices=[(1, 'Normal'), (2, 'Pneumonia'), (3, 'PCP'), (4, 'Cardiomegaly'), (5, 'Pleural effusion')], default=None)),
                ('ECG_findings', models.IntegerField(choices=[(1, 'Normal'), (2, 'Left ventricular hypertrophy'), (3, 'Ischaemic heart disease'), (4, 'Heart arrhythmias')])),
                ('ECHO_findings', models.IntegerField(choices=[(1, 'Normal'), (2, 'Left ventricular hypertrophy'), (3, 'Dystolic dysfunction'), (4, 'Cardiomyopathy'), (5, 'Other')])),
            ],
        ),
        migrations.DeleteModel(
            name='RetroModelEnrol',
        ),
    ]
