# Generated by Django 2.2.5 on 2019-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospective', '0004_auto_20191114_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Blood_glucose',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Blood_pressure_diastolic',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Blood_pressure_systolic',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='CD4_count',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Chest_X_ray_option_1',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Chest_X_ray_option_2',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Current_ARV_regimen',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Date_antiretroviral_therapy_commenced',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Date_of_Birth',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Date_of_CD4_count',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Date_of_Viral_load',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Date_of_form_completion',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Date_patient_enrolled_at_the_clinic',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Did_the_patient_have_Diabetes_when_they_started_attending_the_clinic',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Did_the_patient_have_Hypertension_when_they_started_attending_the_clinic',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='ECG_findings',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='ECHO_findings',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='HDL',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='If_YES_when_was_the_diagnosis_of_diabetes_made',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='If_YES_when_was_the_diagnosis_of_hypertension_made',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='LDL',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='List_of_diabetes_treatment_when_patient_started_attending_the_clinic',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='List_of_hypertension_treatment_when_patient_started_attending_the_clinic',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Patient_Hospital_ID',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Previous_regimen_1_Date_commenced',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Previous_regimen_1_Date_ended',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Previous_regimen_1_Reason_for_shift',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Previous_regimen_2_Date_commenced',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Previous_regimen_2_Date_ended',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Previous_regimen_2_Reason_for_shift',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Serum_urea_levels',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Sex',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Total_cholesterol',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Triglycerides',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Viral_load',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Waist',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Was_this_a_fasting_or_random_blood_glucose',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='enrolmentpatientstartattheclinic',
            name='When_was_the_diagnosis_made',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='If_yes_to_Qn11_question_date_of_diagnosis',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='If_yes_to_Qn12_date_of_diagnosis',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='If_yes_to_Qn13_question_date_of_diagnosis',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='If_yes_to_Qn14_date_of_diagnosis',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Patients_initials',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn10_List_of_hypertension_treatment',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn11_Stroke',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn12_Diabetic_foot',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn13_Chronic_heart_failure',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn14_Chronic_renal_failure',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn1_Date_of_form_completion',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn2_Patient_Hospital_ID',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn3_Date_patient_last_seen_at_the_clinic',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn4_Is_the_patient_alive_and_in_care',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn5_Since_the_patient_started_at_this_clinic_have_they_developed_diabetes',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn6_If_YES_when_was_the_diagnosis_of_diabetes_made',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn7_List_of_diabetes_treatment',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn8_Since_the_patient_started_at_this_clinic_have_they_developed_hypertension',
        ),
        migrations.RemoveField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='Qn9_If_YES_when_was_the_diagnosis_of_hypertension_made',
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='age',
            field=models.CharField(default=0, max_length=3, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='birthday',
            field=models.DateField(default=None, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='blood_glucose',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, verbose_name='Blood glucose'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='bp_diastolic',
            field=models.IntegerField(default=None, verbose_name='Blood pressure Diastolic (mmHg)'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='bp_systolic',
            field=models.IntegerField(default=None, verbose_name='Blood pressure Systolic (mmHg)'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='cd4_count',
            field=models.IntegerField(default=None, verbose_name='CD4 count'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='chest_X_ray_option_1',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Pneumonia'), (3, 'PCP'), (4, 'Cardiomegaly'), (5, 'Pleural effusion')], default=None, verbose_name='Chest X-ray Choose from findings listed (you can enter up to'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='current_arv_regimen',
            field=models.CharField(choices=[(1, 'AZT + 3TC + NVP'), (2, 'AZT + 3TC + EFV'), (3, 'AZT + 3TC + DTG'), (4, 'ABC + 3TC + EFV'), (5, 'ABC + 3TC + DTG'), (6, 'd4T + 3TC + NVP'), (7, 'd4T + 3TC + EFV'), (8, 'TDF + FTC + EFV'), (9, 'TDF + FTC + NVP'), (10, 'TDF + 3TC + EFV'), (11, 'TDF + 3TC + NVP'), (12, 'TDF + 3TC + DTG'), (13, 'TDF + FTC + DTG'), (14, 'TDF + 3TC + ATV/r'), (15, 'TDF + FTC + ATV/r'), (16, 'TDF + 3TC + LPV/r'), (17, 'AZT + 3TC + ATV/r'), (18, 'AZT + 3TC + LPV/r'), (19, 'ABC + 3TC + ATV/r'), (20, 'ABC + 3TC + LPV/r'), (21, 'TDF + FTC + LPV/R'), (22, 'DTG + (ABC/3TC) + ATV/r')], default=None, max_length=2, verbose_name='Current ARV regimen'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='date_arv_commenced',
            field=models.DateField(default=None, verbose_name='Date antiretroviral therapy commenced'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='date_of_CD4_count',
            field=models.DateField(default=None, verbose_name='Date of CD4 count'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='date_of_Viral_load',
            field=models.DateField(default=None, verbose_name='Date of Viral load'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='date_of_completion',
            field=models.DateField(default=None, verbose_name='Date of form completion'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='diabetes_status',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=None, verbose_name='Did the patient have Diabetes when they started attending the clinic?'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='diagnosis_diabetes',
            field=models.DateField(default=None, verbose_name='If YES, when was the diagnosis of diabetes made?'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='diagnosis_hypertension',
            field=models.DateField(default=None, verbose_name='If YES, when was the diagnosis of hypertension made?'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='diagnosis_made',
            field=models.DateField(default=None, verbose_name='When was the diagnosis made?'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='ecg_findings',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Left ventricular hypertrophy'), (3, 'Ischaemic heart disease'), (4, 'Heart arrhythmias')], default=None, verbose_name='ECG findings'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='echo_findings',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Left ventricular hypertrophy'), (3, 'Dystolic dysfunction'), (4, 'Cardiomyopathy'), (5, 'Other')], default=None, verbose_name='ECHO findings'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='enrolled_date',
            field=models.DateField(default=None, verbose_name='Date patient enrolled at the clinic'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='fasting_or_random',
            field=models.CharField(choices=[(1, 'Fasting'), (2, 'Random')], default=None, max_length=4, verbose_name='Was this a fasting or random blood glucose?'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='hdl',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, verbose_name='HDL'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='height',
            field=models.IntegerField(default=None, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='hospital_id',
            field=models.CharField(default=None, max_length=20, verbose_name='Patient Hospital ID'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='hypertension_status',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=None, verbose_name='Did the patient have Hypertension when they started attending the clinic?'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='hypertension_treatment',
            field=models.TextField(default=None, verbose_name='List of hypertension treatment when patient started attending the clinic'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='ldl',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, verbose_name='LDL'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='regime1_reason_for_shift',
            field=models.TextField(default=None, verbose_name='Reason for switching'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='regimen1_commenced',
            field=models.DateField(default=None, verbose_name='Date commenced'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='regimen1_end',
            field=models.DateField(default=None, verbose_name='Date ended'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='regimen2_commenced',
            field=models.DateField(default=None, verbose_name='Date commenced'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='regimen2_ended',
            field=models.DateField(default=None, verbose_name='Date ended'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='regimen2_reason_for_shift',
            field=models.TextField(default=None, verbose_name='Reason for switching'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='serum_urea_levels',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, verbose_name='Serum urea levels (mg/dl)'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='sex',
            field=models.CharField(choices=[(1, 'MALE'), (2, 'FEMALE')], default=None, max_length=6, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='total_cholesterol',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, verbose_name='Total cholesterol'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='treatment_diabetes',
            field=models.TextField(default=None, verbose_name='List of diabetes treatment when patient started attending the clinic'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='triglycerides',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, verbose_name='Triglycerides'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='viral_load',
            field=models.IntegerField(default=None, verbose_name='Viral load'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='waist',
            field=models.IntegerField(default=None, verbose_name='Waist'),
        ),
        migrations.AddField(
            model_name='enrolmentpatientstartattheclinic',
            name='weight',
            field=models.IntegerField(default=None, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='date_completion',
            field=models.DateField(default=None, verbose_name='Date of form completion'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='date_last_seen',
            field=models.DateField(default=None, verbose_name='Date patient last seen at the clinic'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='developed_diabetes',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=None, verbose_name='Since the patient started at this clinic, have they developed diabetes?'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='developed_hypertension',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=None, verbose_name='Since the patient started at this clinic, have they developed hypertension?'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='diabetes_treatment',
            field=models.TextField(default=None, verbose_name='List of diabetes treatment.'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='diabetic_foot',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=None, verbose_name='Diabetic foot'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='diabetic_foot_diagnosis',
            field=models.DateField(default=None, verbose_name='If yes, date of diagnosis'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='diagnosis_diabetes_made',
            field=models.DateField(default=None, verbose_name='If YES, when was the diagnosis of diabetes made?'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='diagnosis_hypertension_made',
            field=models.DateField(default=None, verbose_name='If YES, when was the diagnosis of hypertension made?'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='heart_failure',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=None, verbose_name='Chronic heart failure'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='heart_failure_diagnosis',
            field=models.DateField(default=None, verbose_name='If yes, date of diagnosis'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='hospital_id',
            field=models.CharField(default=None, max_length=20, verbose_name='Patient Hospital ID'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='hypertension_treatment',
            field=models.TextField(default=None, verbose_name='List of hypertension treatment.'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='initials',
            field=models.CharField(default=None, max_length=3, verbose_name='Patients initials'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='patient_alive',
            field=models.IntegerField(choices=[(1, 'Yes, alive and in care at this clinic'), (2, 'Yes, alive and in care elsewhere'), (3, 'No, patient died')], default=None, verbose_name='Is the patient alive and in care?'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='renal_failure',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=None, verbose_name='Chronic renal failure'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='renal_failure_diagnosis',
            field=models.DateField(default=None, verbose_name='If yes, date of diagnosis'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='stroke',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=None, verbose_name='Stroke'),
        ),
        migrations.AddField(
            model_name='hivretrospectivecohortfollowupcrf',
            name='stroke_diagnosis',
            field=models.DateField(default=None, verbose_name='If yes, date of diagnosis'),
        ),
        migrations.AlterField(
            model_name='enrolmentpatientstartattheclinic',
            name='Serum_creatinine_levels',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, verbose_name='Serum creatinine levels (mg/dl)'),
        ),
    ]
