# Generated by Django 3.0.4 on 2020-05-03 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_consent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectconsent",
            name="ctc_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                max_length=36,
                null=True,
                verbose_name="CTC Identifier",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectconsent",
            name="file_number",
            field=models.CharField(
                db_index=True,
                default=uuid.uuid4,
                help_text="Patient file number from Hindu Mandal Hospital",
                max_length=36,
                verbose_name="Patient File number",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectconsent",
            name="hospital_identifier",
            field=models.CharField(
                db_index=True,
                default=uuid.uuid4,
                help_text="Hindu Mandal Hospital Identifier",
                max_length=36,
                verbose_name="HMS Identifier",
            ),
        ),
        migrations.AddField(
            model_name="subjectconsent",
            name="ctc_identifier",
            field=models.CharField(
                blank=True,
                default=uuid.uuid4,
                max_length=36,
                null=True,
                unique=True,
                verbose_name="CTC Identifier",
            ),
        ),
        migrations.AddField(
            model_name="subjectconsent",
            name="file_number",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Patient file number from Hindu Mandal Hospital",
                max_length=36,
                unique=True,
                verbose_name="Patient File number",
            ),
        ),
        migrations.AddField(
            model_name="subjectconsent",
            name="hospital_identifier",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Hindu Mandal Hospital Identifier",
                max_length=36,
                unique=True,
                verbose_name="HMS Identifier",
            ),
        ),
    ]
