# Generated by Django 3.0.4 on 2020-03-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_consent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectconsent",
            name="retrospective_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subjectconsent",
            name="retrospective_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="clinic_type",
            field=models.CharField(
                choices=[
                    ("hiv_clinic", "HIV Clinic"),
                    ("ncd_clinic", "NCD Clinic"),
                    ("integrated_clinic", "Integrated Clinic"),
                ],
                help_text="Should match that reported on the Screening form.",
                max_length=25,
                verbose_name="In which type of clinic was the patient screened",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="clinic_type",
            field=models.CharField(
                choices=[
                    ("hiv_clinic", "HIV Clinic"),
                    ("ncd_clinic", "NCD Clinic"),
                    ("integrated_clinic", "Integrated Clinic"),
                ],
                help_text="Should match that reported on the Screening form.",
                max_length=25,
                verbose_name="In which type of clinic was the patient screened",
            ),
        ),
    ]
