# Generated by Django 3.0.4 on 2020-05-12 00:28

from django.db import migrations


def resave_to_encrypt_identity_fields(apps, schema_editor):
    model_cls = apps.get_model("mapitio_consent", "SubjectConsent")
    for obj in model_cls.objects.all():
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_consent", "0005_auto_20200512_0328"),
    ]

    operations = [migrations.RunPython(resave_to_encrypt_identity_fields)]
