# Generated by Django 3.0.4 on 2020-03-27 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0002_alter_domain_unique"),
        ("mapitio_prn", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalOnScheduleHiv", new_name="HistoricalOnSchedule",
        ),
        migrations.RenameModel(old_name="OnScheduleHiv", new_name="OnSchedule",),
        migrations.RemoveField(
            model_name="historicalonschedulencd", name="history_user",
        ),
        migrations.RemoveField(model_name="historicalonschedulencd", name="site",),
        migrations.RemoveField(model_name="onschedulencd", name="site",),
        migrations.AlterModelOptions(
            name="historicalonschedule",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical on schedule",
            },
        ),
        migrations.RemoveIndex(
            model_name="onschedule", name="mapitio_prn_id_d34285_idx",
        ),
        migrations.AddIndex(
            model_name="onschedule",
            index=models.Index(
                fields=["id", "subject_identifier", "onschedule_datetime", "site"],
                name="mapitio_prn_id_dfd202_idx",
            ),
        ),
        migrations.DeleteModel(name="HistoricalOnScheduleNcd",),
        migrations.DeleteModel(name="OnScheduleNcd",),
    ]
