# Generated by Django 3.0.4 on 2020-04-09 03:32

from django.db import migrations, models
import edc_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_subject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhivhistory",
            name="other_current_regimen",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="hivhistory",
            name="other_current_regimen",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="enrolment",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="historicalenrolment",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
