# Generated by Django 3.0.4 on 2020-03-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_subject", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="subjectconsent", unique_together=None,),
        migrations.RemoveField(model_name="subjectconsent", name="site",),
        migrations.DeleteModel(name="HistoricalSubjectConsent",),
        migrations.DeleteModel(name="SubjectConsent",),
    ]
