# Generated by Django 3.0.4 on 2020-04-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_lists", "0001_initial"),
        ("mapitio_subject", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="historicalhivhistory", name="diabetes_rx",),
        migrations.RemoveField(
            model_name="historicalhivhistory", name="hypertension_rx",
        ),
        migrations.RemoveField(model_name="historicalncdfollowup", name="diabetes_rx",),
        migrations.RemoveField(
            model_name="historicalncdfollowup", name="hypertension_rx",
        ),
        migrations.RemoveField(
            model_name="historicalncdhistory", name="cholesterol_rx",
        ),
        migrations.RemoveField(model_name="historicalncdhistory", name="diabetes_rx",),
        migrations.RemoveField(
            model_name="historicalncdhistory", name="hypertension_rx",
        ),
        migrations.RemoveField(model_name="hivhistory", name="diabetes_rx",),
        migrations.AddField(
            model_name="hivhistory",
            name="diabetes_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.DiabetesMedications",
                verbose_name="If YES, diabetes treatment",
            ),
        ),
        migrations.RemoveField(model_name="hivhistory", name="hypertension_rx",),
        migrations.AddField(
            model_name="hivhistory",
            name="hypertension_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.HypertensionMedications",
                verbose_name="If YES, hypertension treatment",
            ),
        ),
        migrations.RemoveField(model_name="ncdfollowup", name="diabetes_rx",),
        migrations.AddField(
            model_name="ncdfollowup",
            name="diabetes_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.DiabetesMedications",
                verbose_name="If YES, diabetes treatment",
            ),
        ),
        migrations.RemoveField(model_name="ncdfollowup", name="hypertension_rx",),
        migrations.AddField(
            model_name="ncdfollowup",
            name="hypertension_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.HypertensionMedications",
                verbose_name="If YES, hypertension treatment",
            ),
        ),
        migrations.RemoveField(model_name="ncdhistory", name="cholesterol_rx",),
        migrations.AddField(
            model_name="ncdhistory",
            name="cholesterol_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.CholesterolMedications",
                verbose_name="If YES, blood cholesterol medications",
            ),
        ),
        migrations.RemoveField(model_name="ncdhistory", name="diabetes_rx",),
        migrations.AddField(
            model_name="ncdhistory",
            name="diabetes_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.DiabetesMedications",
                verbose_name="If YES, diabetes treatment",
            ),
        ),
        migrations.RemoveField(model_name="ncdhistory", name="hypertension_rx",),
        migrations.AddField(
            model_name="ncdhistory",
            name="hypertension_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.HypertensionMedications",
                verbose_name="If YES, hypertension treatment",
            ),
        ),
    ]
