# Generated by Django 3.0.4 on 2020-04-30 01:41

from django.db import migrations
import edc_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_subject", "0003_auto_20200430_0415"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalncdhistory",
            name="other_cholesterol_rx",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="ncdhistory",
            name="other_cholesterol_rx",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
    ]
