# Generated by Django 3.0.4 on 2020-04-30 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_lists", "0001_initial"),
        ("mapitio_subject", "0004_auto_20200430_0441"),
    ]

    operations = [
        migrations.RemoveField(model_name="biomedicalfollowup", name="alp_units",),
        migrations.RemoveField(model_name="biomedicalfollowup", name="alt_units",),
        migrations.RemoveField(model_name="biomedicalfollowup", name="amylase_units",),
        migrations.RemoveField(model_name="biomedicalfollowup", name="ast_units",),
        migrations.RemoveField(model_name="biomedicalfollowup", name="drawn_date",),
        migrations.RemoveField(model_name="biomedicalfollowup", name="ggt_units",),
        migrations.RemoveField(model_name="biomedicalhistory", name="alp_units",),
        migrations.RemoveField(model_name="biomedicalhistory", name="alt_units",),
        migrations.RemoveField(model_name="biomedicalhistory", name="amylase_units",),
        migrations.RemoveField(model_name="biomedicalhistory", name="ast_units",),
        migrations.RemoveField(model_name="biomedicalhistory", name="drawn_date",),
        migrations.RemoveField(model_name="biomedicalhistory", name="ggt_units",),
        migrations.RemoveField(
            model_name="historicalbiomedicalfollowup", name="alp_units",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalfollowup", name="alt_units",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalfollowup", name="amylase_units",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalfollowup", name="ast_units",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalfollowup", name="drawn_date",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalfollowup", name="ggt_units",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalhistory", name="alp_units",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalhistory", name="alt_units",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalhistory", name="amylase_units",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalhistory", name="ast_units",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalhistory", name="drawn_date",
        ),
        migrations.RemoveField(
            model_name="historicalbiomedicalhistory", name="ggt_units",
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="albumin_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum Albumin date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="alp_date",
            field=models.DateField(blank=True, null=True, verbose_name="ALP date"),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="alt_date",
            field=models.DateField(blank=True, null=True, verbose_name="ALT date"),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="amylase_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum Amylase date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="ast_date",
            field=models.DateField(blank=True, null=True, verbose_name="AST date"),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="ggt_date",
            field=models.DateField(blank=True, null=True, verbose_name="GGT date"),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="hbsag_date",
            field=models.DateField(blank=True, null=True, verbose_name="HbSAg date"),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="hcv_date",
            field=models.DateField(blank=True, null=True, verbose_name="HCV date"),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="hdl_date",
            field=models.DateField(blank=True, null=True, verbose_name="HDL date"),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="ldl_date",
            field=models.DateField(blank=True, null=True, verbose_name="LDL date"),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="serum_creatinine_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum creatinine date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="serum_urea_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum urea date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="serum_uric_acid_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum uric acid date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="total_cholesterol_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Total cholesterol date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalfollowup",
            name="triglycerides_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Triglycerides date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="albumin_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum Albumin date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="alp_date",
            field=models.DateField(blank=True, null=True, verbose_name="ALP date"),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="alt_date",
            field=models.DateField(blank=True, null=True, verbose_name="ALT date"),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="amylase_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum Amylase date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="ast_date",
            field=models.DateField(blank=True, null=True, verbose_name="AST date"),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="ggt_date",
            field=models.DateField(blank=True, null=True, verbose_name="GGT date"),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="hbsag_date",
            field=models.DateField(blank=True, null=True, verbose_name="HbSAg date"),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="hcv_date",
            field=models.DateField(blank=True, null=True, verbose_name="HCV date"),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="hdl_date",
            field=models.DateField(blank=True, null=True, verbose_name="HDL date"),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="ldl_date",
            field=models.DateField(blank=True, null=True, verbose_name="LDL date"),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="serum_creatinine_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum creatinine date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="serum_urea_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum urea date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="serum_uric_acid_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum uric acid date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="total_cholesterol_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Total cholesterol date"
            ),
        ),
        migrations.AddField(
            model_name="biomedicalhistory",
            name="triglycerides_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Triglycerides date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="albumin_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum Albumin date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="alp_date",
            field=models.DateField(blank=True, null=True, verbose_name="ALP date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="alt_date",
            field=models.DateField(blank=True, null=True, verbose_name="ALT date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="amylase_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum Amylase date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="ast_date",
            field=models.DateField(blank=True, null=True, verbose_name="AST date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="ggt_date",
            field=models.DateField(blank=True, null=True, verbose_name="GGT date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="hbsag_date",
            field=models.DateField(blank=True, null=True, verbose_name="HbSAg date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="hcv_date",
            field=models.DateField(blank=True, null=True, verbose_name="HCV date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="hdl_date",
            field=models.DateField(blank=True, null=True, verbose_name="HDL date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="ldl_date",
            field=models.DateField(blank=True, null=True, verbose_name="LDL date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="serum_creatinine_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum creatinine date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="serum_urea_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum urea date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="serum_uric_acid_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum uric acid date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="total_cholesterol_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Total cholesterol date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalfollowup",
            name="triglycerides_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Triglycerides date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="albumin_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum Albumin date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="alp_date",
            field=models.DateField(blank=True, null=True, verbose_name="ALP date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="alt_date",
            field=models.DateField(blank=True, null=True, verbose_name="ALT date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="amylase_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum Amylase date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="ast_date",
            field=models.DateField(blank=True, null=True, verbose_name="AST date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="ggt_date",
            field=models.DateField(blank=True, null=True, verbose_name="GGT date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="hbsag_date",
            field=models.DateField(blank=True, null=True, verbose_name="HbSAg date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="hcv_date",
            field=models.DateField(blank=True, null=True, verbose_name="HCV date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="hdl_date",
            field=models.DateField(blank=True, null=True, verbose_name="HDL date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="ldl_date",
            field=models.DateField(blank=True, null=True, verbose_name="LDL date"),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="serum_creatinine_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum creatinine date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="serum_urea_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum urea date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="serum_uric_acid_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Serum uric acid date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="total_cholesterol_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Total cholesterol date"
            ),
        ),
        migrations.AddField(
            model_name="historicalbiomedicalhistory",
            name="triglycerides_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Triglycerides date"
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalfollowup",
            name="alp",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="ALP",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalfollowup",
            name="alt",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="ALT",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalfollowup",
            name="amylase",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="Serum Amylase",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalfollowup",
            name="ast",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="AST",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalfollowup",
            name="ggt",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="GGT",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalfollowup",
            name="serum_creatinine",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum creatinine",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalfollowup",
            name="serum_creatinine_units",
            field=models.CharField(
                blank=True,
                choices=[("mg/dL", "mg/dL"), ("mmol/L", "mmol/L")],
                max_length=15,
                null=True,
                verbose_name="Serum creatinine units ",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalfollowup",
            name="serum_urea",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum urea",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalfollowup",
            name="serum_uric_acid",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum uric acid",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalfollowup",
            name="total_cholesterol",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="mmol/L",
                max_digits=4,
                null=True,
                verbose_name="Total cholesterol",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalhistory",
            name="alp",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="ALP",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalhistory",
            name="alt",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="ALT",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalhistory",
            name="amylase",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="Serum Amylase",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalhistory",
            name="ast",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="AST",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalhistory",
            name="ggt",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="GGT",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalhistory",
            name="serum_creatinine",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum creatinine",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalhistory",
            name="serum_creatinine_units",
            field=models.CharField(
                blank=True,
                choices=[("mg/dL", "mg/dL"), ("mmol/L", "mmol/L")],
                max_length=15,
                null=True,
                verbose_name="Serum creatinine units ",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalhistory",
            name="serum_urea",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum urea",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalhistory",
            name="serum_uric_acid",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum uric acid",
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalhistory",
            name="total_cholesterol",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="mmol/L",
                max_digits=4,
                null=True,
                verbose_name="Total cholesterol",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalfollowup",
            name="alp",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="ALP",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalfollowup",
            name="alt",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="ALT",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalfollowup",
            name="amylase",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="Serum Amylase",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalfollowup",
            name="ast",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="AST",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalfollowup",
            name="ggt",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="GGT",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalfollowup",
            name="serum_creatinine",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum creatinine",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalfollowup",
            name="serum_creatinine_units",
            field=models.CharField(
                blank=True,
                choices=[("mg/dL", "mg/dL"), ("mmol/L", "mmol/L")],
                max_length=15,
                null=True,
                verbose_name="Serum creatinine units ",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalfollowup",
            name="serum_urea",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum urea",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalfollowup",
            name="serum_uric_acid",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum uric acid",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalfollowup",
            name="total_cholesterol",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="mmol/L",
                max_digits=4,
                null=True,
                verbose_name="Total cholesterol",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalhistory",
            name="alp",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="ALP",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalhistory",
            name="alt",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="ALT",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalhistory",
            name="amylase",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="Serum Amylase",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalhistory",
            name="ast",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="AST",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalhistory",
            name="ggt",
            field=models.IntegerField(
                blank=True,
                help_text="U/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="GGT",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalhistory",
            name="serum_creatinine",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum creatinine",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalhistory",
            name="serum_creatinine_units",
            field=models.CharField(
                blank=True,
                choices=[("mg/dL", "mg/dL"), ("mmol/L", "mmol/L")],
                max_length=15,
                null=True,
                verbose_name="Serum creatinine units ",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalhistory",
            name="serum_urea",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum urea",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalhistory",
            name="serum_uric_acid",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Serum uric acid",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiomedicalhistory",
            name="total_cholesterol",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="mmol/L",
                max_digits=4,
                null=True,
                verbose_name="Total cholesterol",
            ),
        ),
        migrations.AlterField(
            model_name="historicalncdhistory",
            name="smoking_status",
            field=models.CharField(
                choices=[
                    ("smoker", "Currently smokes"),
                    ("former_smoker", "Used to smoke but stopped"),
                    ("nonsmoker", "Never smoked"),
                    ("not_recorded", "Not recorded"),
                ],
                max_length=15,
                verbose_name="Smoker? Which best describes the patient:",
            ),
        ),
        migrations.AlterField(
            model_name="hivhistory",
            name="diabetes_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.DiabetesMedications",
                verbose_name="Diabetes treatment",
            ),
        ),
        migrations.AlterField(
            model_name="hivhistory",
            name="hypertension_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.HypertensionMedications",
                verbose_name="Hypertension treatment",
            ),
        ),
        migrations.AlterField(
            model_name="ncdfollowup",
            name="diabetes_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.DiabetesMedications",
                verbose_name="Diabetes treatment",
            ),
        ),
        migrations.AlterField(
            model_name="ncdfollowup",
            name="hypertension_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.HypertensionMedications",
                verbose_name="Hypertension treatment",
            ),
        ),
        migrations.AlterField(
            model_name="ncdhistory",
            name="diabetes_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.DiabetesMedications",
                verbose_name="Diabetes treatment",
            ),
        ),
        migrations.AlterField(
            model_name="ncdhistory",
            name="hypertension_rx",
            field=models.ManyToManyField(
                to="mapitio_lists.HypertensionMedications",
                verbose_name="Hypertension treatment",
            ),
        ),
        migrations.AlterField(
            model_name="ncdhistory",
            name="smoking_status",
            field=models.CharField(
                choices=[
                    ("smoker", "Currently smokes"),
                    ("former_smoker", "Used to smoke but stopped"),
                    ("nonsmoker", "Never smoked"),
                    ("not_recorded", "Not recorded"),
                ],
                max_length=15,
                verbose_name="Smoker? Which best describes the patient:",
            ),
        ),
    ]
