# Generated by Django 3.0.4 on 2020-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_subject", "0004_auto_20200504_1746"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvestigations",
            name="chest_xray_findings_documented",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=25,
                verbose_name="Were the chest x-ray findings documented?",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="chest_xray_requested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=25,
                verbose_name="Was a chest x-ray requested?",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="ecg_findings_documented",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=25,
                verbose_name="Were the ECG findings documented?",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="ecg_requested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=25,
                verbose_name="Was an ECG requested?",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="echo_findings_documented",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=25,
                verbose_name="Were the ECHO findings documented?",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="echo_requested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=25,
                verbose_name="Was an ECHO requested?",
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="chest_xray_findings_documented",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=25,
                verbose_name="Were the chest x-ray findings documented?",
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="chest_xray_requested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=25,
                verbose_name="Was a chest x-ray requested?",
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="ecg_findings_documented",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=25,
                verbose_name="Were the ECG findings documented?",
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="ecg_requested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=25,
                verbose_name="Was an ECG requested?",
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="echo_findings_documented",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=25,
                verbose_name="Were the ECHO findings documented?",
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="echo_requested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=25,
                verbose_name="Was an ECHO requested?",
            ),
        ),
    ]
