# Generated by Django 3.0.4 on 2020-05-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_lists", "0001_initial"),
        ("mapitio_subject", "0005_auto_20200506_1958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hivhistory",
            name="diabetes_rx",
            field=models.ManyToManyField(
                blank=True,
                to="mapitio_lists.DiabetesMedications",
                verbose_name="Diabetes treatment",
            ),
        ),
        migrations.AlterField(
            model_name="hivhistory",
            name="hypertension_rx",
            field=models.ManyToManyField(
                blank=True,
                to="mapitio_lists.HypertensionMedications",
                verbose_name="Hypertension treatment",
            ),
        ),
        migrations.AlterField(
            model_name="ncdfollowup",
            name="diabetes_rx",
            field=models.ManyToManyField(
                blank=True,
                to="mapitio_lists.DiabetesMedications",
                verbose_name="Diabetes treatment",
            ),
        ),
        migrations.AlterField(
            model_name="ncdfollowup",
            name="hypertension_rx",
            field=models.ManyToManyField(
                blank=True,
                to="mapitio_lists.HypertensionMedications",
                verbose_name="Hypertension treatment",
            ),
        ),
        migrations.AlterField(
            model_name="ncdhistory",
            name="diabetes_rx",
            field=models.ManyToManyField(
                blank=True,
                to="mapitio_lists.DiabetesMedications",
                verbose_name="Diabetes treatment",
            ),
        ),
        migrations.AlterField(
            model_name="ncdhistory",
            name="hypertension_rx",
            field=models.ManyToManyField(
                blank=True,
                to="mapitio_lists.HypertensionMedications",
                verbose_name="Hypertension treatment",
            ),
        ),
    ]
