# Generated by Django 3.0.4 on 2020-05-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_lists", "0001_initial"),
        ("mapitio_subject", "0006_auto_20200506_2132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ncdhistory",
            name="cholesterol_rx",
            field=models.ManyToManyField(
                blank=True,
                to="mapitio_lists.CholesterolMedications",
                verbose_name="If YES, blood cholesterol medications",
            ),
        ),
    ]
