# Generated by Django 3.0.4 on 2020-04-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_subject", "0007_auto_20200501_0052"),
    ]

    operations = [
        migrations.RemoveField(model_name="historicalenrollment", name="history_user",),
        migrations.RemoveField(model_name="historicalenrollment", name="site",),
        migrations.DeleteModel(name="Enrollment",),
        migrations.DeleteModel(name="HistoricalEnrollment",),
    ]
