# Generated by Django 3.0.4 on 2020-05-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_subject", "0009_auto_20200507_0616"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="followup",
            options={"verbose_name": "Followup", "verbose_name_plural": "Followups"},
        ),
        migrations.AlterModelOptions(
            name="historicalfollowup",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Followup",
            },
        ),
    ]
