# Generated by Django 3.0.4 on 2020-05-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_subject", "0009_auto_20200501_0318"),
    ]

    operations = [
        migrations.RenameField(
            model_name="followup", old_name="survival_status", new_name="alive",
        ),
        migrations.RenameField(
            model_name="historicalfollowup",
            old_name="survival_status",
            new_name="alive",
        ),
    ]
