# Generated by Django 3.0.4 on 2020-05-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapitio_subject", "0010_auto_20200512_0234"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biomedicalfollowup",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Biomedical Followup",
                "verbose_name_plural": "Biomedical Followup",
            },
        ),
        migrations.AlterModelOptions(
            name="biomedicalhistory",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Biomedical History",
                "verbose_name_plural": "Biomedical History",
            },
        ),
        migrations.AlterModelOptions(
            name="complications",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Complications",
                "verbose_name_plural": "Complications",
            },
        ),
        migrations.AlterModelOptions(
            name="deathreport",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Death Report",
                "verbose_name_plural": "Death Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="followup",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Followup",
                "verbose_name_plural": "Followups",
            },
        ),
        migrations.AlterModelOptions(
            name="followupindicators",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Followup Indicators",
                "verbose_name_plural": "Followup Indicators",
            },
        ),
        migrations.AlterModelOptions(
            name="hivfollowup",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "HIV Followup",
                "verbose_name_plural": "HIV Followup",
            },
        ),
        migrations.AlterModelOptions(
            name="hivhistory",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "HIV History",
                "verbose_name_plural": "HIV History",
            },
        ),
        migrations.AlterModelOptions(
            name="indicators",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Indicators",
                "verbose_name_plural": "Indicators",
            },
        ),
        migrations.AlterModelOptions(
            name="investigations",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Investigations",
                "verbose_name_plural": "Investigations",
            },
        ),
        migrations.AlterModelOptions(
            name="ncdfollowup",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "NCD Followup",
                "verbose_name_plural": "NCD Followup",
            },
        ),
        migrations.AlterModelOptions(
            name="ncdhistory",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "NCD History",
                "verbose_name_plural": "NCD History",
            },
        ),
    ]
