# Generated by Django 3.0.4 on 2020-05-01 03:14

from django.db import migrations, models
import edc_model.validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('mapitio_subject', '0011_auto_20200501_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathreport',
            name='death_date',
            field=models.DateField(validators=[edc_model.validators.date.date_is_past], verbose_name='Date of death'),
        ),
        migrations.AlterField(
            model_name='historicaldeathreport',
            name='death_date',
            field=models.DateField(validators=[edc_model.validators.date.date_is_past], verbose_name='Date of death'),
        ),
    ]
